version: "3.4"

networks:
  logging-network:
    driver: bridge
  nba-network:
    driver: bridge

services:
  database:
    container_name: postgresql-13
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: Str0ngPassword!
      POSTGRES_DB: petrelcore
      POSTGRES_ADMIN_PASSWORD: Str0ngPassword!
    ports:
      - 5432:5432
    networks:
      - nba-network

  identityserver:
    container_name: nba-identity-server
    image: nba/nbaidentityserver
    restart: "no"
    depends_on:
      - database
    build:
      context: ./src
      dockerfile: Dockerfile_Identity
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:44393
      ASPNETCORE_HTTPS_PORT: 44393
      ConnectionStrings:DefaultConnection: Server=database;Port=5432;Database=petrelcore;User Id=postgres;Password=Str0ngPassword!
    ports:
      - 44393:44393
    networks:
      - nba-network
    volumes:
      - ~/.aspnet/https:/https:ro

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - logging-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - logging-network

volumes:
  elasticsearch-data:
