version: "3.4"

networks:
  logging-network:
    driver: bridge
  nba-network:
    driver: bridge

services:
  database.identity:
    container_name: nba-identity-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: identity
      POSTGRES_ADMIN_PASSWORD: Str0ngPass!
    ports:
      - 5433:5432
    networks:
      - nba-network

  database.api:
    container_name: nba-api-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: core
      POSTGRES_ADMIN_PASSWORD: Str0ngPass!
    ports:
      - 5432:5432
    networks:
      - nba-network

  identityserver:
    container_name: nba-identity-server
    image: nba/nbaidentityserver
    restart: "no"
    depends_on:
      - database.identity
      - elasticsearch
      - rabbitmq
    build:
      context: ./src
      dockerfile: Dockerfile_Identity
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:44393
      ASPNETCORE_HTTPS_PORT: 44393
      ElasticSearch:ConnectionString: http://elasticsearch:9200
      MessageBroker:RabbitHost: "rabbitmq://admin:admin@rabbitmq:5672"
      MessageBroker:KafkaHost: kafka:9093
      IssuerUri: https://identityserver
      ConnectionStrings:DefaultConnection: Host=database.identity;Database=identity;User Id=dbuser;Password=Str0ngPass!
    ports:
      - 44393:44393
    networks:
      - nba-network
    volumes:
      - ~/.aspnet/https:/https:ro

  api:
    container_name: nba-api
    image: nba/api
    restart: always
    depends_on:
      - database.api
      - rabbitmq
      - elasticsearch
      - identityserver
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:44338
      ASPNETCORE_HTTPS_PORT: 44338
      ConnectionStrings:DefaultConnection: Host=database.api;Database=core;User Id=dbUser;Password=Str0ngPass!
      ElasticSearch:ConnectionString: http://elasticsearch:9200
      IdentityServer:Authority: https://identityserver:44393
      MessageBroker:RabbitHost: "rabbitmq://admin:admin@rabbitmq:5672"
      MessageBroker:KafkaHost: kafka:9093
    ports:
      - 44338:44338
    networks:
      - nba-network
    volumes:
      - ~/.aspnet/https:/https:ro

  elasticsearch:
    container_name: nba-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - nba-network
      - logging-network

  kibana:
    container_name: nba-kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - nba-network
      - logging-network

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.9-management
    container_name: nba-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - nba-network

  zookeeper:
    container_name: nba-zookeeper
    restart: always
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - nba-network

  # https://www.kaaproject.org/blog/kafka-docker
  kafka:
    container_name: nba-kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "user-change-queue:1:1,healthcheck-topic:1:1"
    networks:
      - nba-network

volumes:
  elasticsearch-data:
