version: "3.8"

services:
  database:
    container_name: postgresql-13
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Str0ngPassword!
      POSTGRESQL_DATABASE: core
    volumes:
      - /var/postgresql/data:/var/lib/postgresql/data
    networks:
      - postgresql
    ports:
      - 5432:5432

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:4.26
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: maintainer@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      - postgresql

networks:
  postgresql:
    driver: bridge
